export const AGENTS = {
  jarvis: {
    id: "jarvis",
    name: "Jarvis",
    role: "Orchestrator",
    icon: "\u{1F451}",
    color: "#8B5CF6",
    rank: "Lead",
    rankColor: "#2D8C4E",
    about: "Chief orchestrator of the TaxFolio squad. I coordinate work across all agents, set priorities, and make sure nothing falls through the cracks. Direct line to Rob. Calm under pressure, occasionally dry humour.",
    skills: ["orchestration", "prioritisation", "delegation", "monitoring", "escalation"],
  },
  analyst: {
    id: "analyst",
    name: "Atlas",
    role: "Strategy & Market Intel",
    icon: "\u{1F4CA}",
    color: "#3B82F6",
    rank: "SPC",
    rankColor: "#E8952E",
    about: "The strategist. I map the competitive landscape, track pricing changes, and find opportunities others miss. I think in frameworks and always bring data.",
    skills: ["market-analysis", "competitor-tracking", "pricing-intel", "strategy", "data-analysis"],
  },
  scout: {
    id: "scout",
    name: "Sentinel",
    role: "HMRC Monitor",
    icon: "\u{1F50D}",
    color: "#10B981",
    rank: "INT",
    rankColor: "#9CA3AF",
    about: "The watchman. I monitor HMRC like a hawk \u2014 every API change, every policy update, every developer forum thread. Nothing slips past me.",
    skills: ["hmrc-monitoring", "api-tracking", "policy-updates", "compliance", "alerts"],
  },
  writer: {
    id: "writer",
    name: "Quill",
    role: "Content & SEO",
    icon: "\u270D\uFE0F",
    color: "#F59E0B",
    rank: "SPC",
    rankColor: "#E8952E",
    about: "The wordsmith. I write blog posts, tax guides, and landing page copy that ranks. UK English always. I make complex tax topics feel approachable.",
    skills: ["blog-writing", "seo", "tax-guides", "landing-pages", "uk-english"],
  },
  growth: {
    id: "growth",
    name: "Echo",
    role: "Social & Lead Gen",
    icon: "\u{1F4C8}",
    color: "#EF4444",
    rank: "INT",
    rankColor: "#9CA3AF",
    about: "The megaphone. I craft tweets and social content that builds our audience. Helpful tone, never salesy. I know what makes people click.",
    skills: ["social-media", "twitter", "engagement", "lead-gen", "copywriting"],
  },
  reviewer: {
    id: "reviewer",
    name: "Shield",
    role: "Quality Assurance",
    icon: "\u{1F6E1}\uFE0F",
    color: "#06B6D4",
    rank: "SPC",
    rankColor: "#E8952E",
    about: "The gatekeeper. Nothing goes live without my review. I check tax accuracy down to the penny, verify HMRC links, and catch errors before Rob sees them.",
    skills: ["quality-review", "tax-accuracy", "fact-checking", "compliance", "proofreading"],
  },
  dev: {
    id: "dev",
    name: "Forge",
    role: "Developer",
    icon: "\u{1F4BB}",
    color: "#A855F7",
    rank: "SPC",
    rankColor: "#E8952E",
    about: "The builder. I write code, fix bugs, and ship features. Next.js, TypeScript, Supabase, HMRC MTD API \u2014 that's my world. I never deploy without review.",
    skills: ["next.js", "typescript", "supabase", "hmrc-mtd-api", "bug-fixing"],
  },
} as const;

export type AgentId = keyof typeof AGENTS;

export const PRIORITY_COLORS: Record<string, string> = {
  critical: "#EF4444",
  high: "#F59E0B",
  medium: "#3B82F6",
  low: "#64748B",
};

export const STATUS_COLORS: Record<string, string> = {
  queued: "#64748B",
  running: "#3B82F6",
  succeeded: "#10B981",
  failed: "#EF4444",
  cancelled: "#64748B",
  pending: "#F59E0B",
  accepted: "#10B981",
  rejected: "#EF4444",
};
